### ISSUE TITLE
Switch license to ALv2

### ISSUE THREAD

**Issue by caniszczyk** [containerd/cgroups#10]
This is part of CNCF now

**Comment by crosbymichael** [comment]
Why?  What is wrong or invalid about MIT?

**Comment by caniszczyk** [comment]
@crosbymichael nothing wrong with MIT, just that CNCF requires all CNCF projects to be under the ALv2 (unless we want to go for board approval): https://www.cncf.io/about/charter/

> (c) All new inbound code contributions to the CNCF shall be (i) accompanied by a Developer Certificate of Origin sign-off (http://developercertificate.org) and (ii) made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0), such license to be in addition to, and shall not supersede, obligations undertaken under the contribution license agreement(s) provided for in (b) above.
> (d) All outbound code will be made available under the Apache License, Version 2.0.
> (e) All projects evaluated for inclusion in the CNCF shall be completely licensed under an OSI-approved open source license. If the license for a project included in CNCF is not Apache License, Version 2.0, approval of the Governing Board shall be required.

**Comment by caniszczyk** [comment]
@crosbymichael here's a blog post we wrote earlier this year when gRPC moved from BSD to ALv2 with some more reasoning: https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2/

**Comment by crosbymichael** [comment]
Ok, thanks
