### ISSUE TITLE
undefined: specs.LinuxRdma

### ISSUE THREAD

**Issue by dean2021** [containerd/cgroups#101]
# go get -v github.com/containerd/cgroups@master

go: finding github.com/containerd/cgroups master
github.com/containerd/cgroups
# github.com/containerd/cgroups
/root/go/pkg/mod/github.com/containerd/cgroups@v0.0.0-20191011165608-5fbad35c2a7e/rdma.go:49:45: undefined: specs.LinuxRdma
/root/go/pkg/mod/github.com/containerd/cgroups@v0.0.0-20191011165608-5fbad35c2a7e/rdma.go:68:38: resources.Rdma undefined (type *specs.LinuxResources has no field or method Rdma)

My go.mod file:

```
module demo1

go 1.13
require (
	github.com/containerd/cgroups v0.0.0-20191011165608-5fbad35c2a7e // indirect
	github.com/opencontainers/runtime-spec v1.0.1 // indirect
)
```

**Comment by paravmellanox** [comment]
@dean2021 didnt get a chance to look at it. Will see tomorrow.
Suspect is the runtime-spec version might not be upto date leading to this error.

**Comment by paravmellanox** [comment]
@dean2021 sorry for my late reply.
May be your cache id old, or something got fixed?

I was able to follow the steps and dont face any compile errors.

**Comment by AkihiroSuda** [comment]
I assume this issue is closable. Please try vendoring the latest revision.
