### ISSUE TITLE
How to modify root path /sys/fs/cgroup

### ISSUE THREAD

**Issue by xianlubird** [containerd/cgroups#132]
I find that the default path is /sys/fs/cgroup

If I run cgroups process in contaienr and mount host cgroups into container ,how should I change the `/sys/fs/cgroups` to another path like `/mycontainer/sys/fs/cgoups`

**Comment by Zyqsempai** [comment]
Something like this for `cgroupv1`:
`control, err := cgroups.New(cgroups.V1, cgroups.StaticPath("/mycontainer/sys/fs/cgoups"), nil)`
and for `cgroupv2`:
`c, err := v2.NewManager("/mycontainer/sys/fs/cgoups", "group-name", nil)`
