### ISSUE TITLE
Upgrade github.com/coreos/go-systemd to v22

### ISSUE THREAD

**Issue by oschwald** [containerd/cgroups#136]
This project currently depends on a version of `github.com/coreos/go-systemd` that didn't use Go modules. This led to the following error when doing a `go get -u all ./...`:

```
go: finding github.com/coreos/go-systemd latest
go get all: no matching versions for query "upgrade" (current version is v0.0.0-20190321100706-95778dfbb74e)
```

I think this could be resolved by updating to v22, which uses Go modules.

**Comment by gzg1984** [comment]
how to update mannually? I met same problem
