### ISSUE TITLE
cgroup2: support statting memory.events*

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/cgroups#149]
The PR for `docker stats` (https://github.com/moby/moby/pull/40657) require `containerd/cgroups` support for `memory.events*`.

**EDIT**: What we can add now seems only `FailCnt`, and this is not urgent (not used by `docker` CLI)

**Comment by Zyqsempai** [comment]
I will work on this!

**Comment by AkihiroSuda** [comment]
@Zyqsempai  What we can add now seems only FailCnt, and this is not urgent (not used by docker CLI)

**Comment by Zyqsempai** [comment]
@AkihiroSuda As far as I can see in cgroupv2  `memory.events -> max` can be interpreted as memory.FailCnt, what do you think?

**Comment by AkihiroSuda** [comment]
Seems yes
