### ISSUE TITLE
Support for other memory cgroup notifications (v1)

### ISSUE THREAD

**Issue by dcantah** [containerd/cgroups#153]
Is there a reason why the oom notification is the only one currently implemented for memory cgroups in v1? I believe memory.usage_in_bytes, memory.memsw.usage_in_bytes and memory.pressure_level all support the notification API as stated in https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt. I can make a pr to add support for these if its not blocked by something.

**Comment by AkihiroSuda** [comment]
Contribution is appreciated

**Comment by dcantah** [comment]
Cool I'll work on it

**Comment by dcantah** [comment]
https://github.com/containerd/cgroups/pull/154
