### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by hiroakis** [containerd/cgroups#19]
When I run `go get github.com/containerd/cgroups`, I've got following errors. How do I resolve this?

```
# github.com/containerd/cgroups
../../containerd/cgroups/blkio.go:301: cannot use st.Rdev (type int32) as type uint64 in argument to major
../../containerd/cgroups/blkio.go:301: cannot use st.Rdev (type int32) as type uint64 in argument to minor
../../containerd/cgroups/memory.go:158: undefined: unix.SYS_EVENTFD2
```

* macOS Sierra 10.12.5
* uname -a
  * Darwin Hiroaki-no-MacBook-Pro-2.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
* go version
  * go1.8.3 darwin/amd64

**Comment by dqminh** [comment]
Its because of `cgroups` is intended to be used/compiled on linux based system, so you cant `go get` it on macOS. If you want to get this for developing in a VM for example, i guess you can also clone the repo directly into your GOPATH.

**Comment by hiroakis** [comment]
@dqminh Thank you for telling me. I understand this matter. I'll close the issue. Thx.
