### ISSUE TITLE
cgroups.go: Panic on nil interface

### ISSUE THREAD

**Issue by linrl3** [containerd/cgroups#205]
https://github.com/containerd/cgroups/blob/main/cgroup.go#L330

If we pass a subsystem that doesn't exist into `func (c *cgroup) Processes(subsystem Name, recursive bool)`, we would get a panic: interface conversion: interface is nil, not cgroups.pather. 

Could I make a patch here to check nil interface before we convert it? Just return error instead of panic.

**Comment by fuweid** [comment]
I think the line 326 can guarantee that subsystem should exist.

**Comment by linrl3** [comment]
@fuweid My code `main.go` was as below. 
```
package main

import (
	"fmt"

	"github.com/containerd/cgroups"
)

var (
	cgroupPath = "/my-test"
	group      = "memory"
)

func main() {
	checkCgroupProcess(cgroupPath, group)
}
func checkCgroupProcess(name string, group string) {
	fmt.Printf("Checking cgroup [%s] process in [%s]\n ", name, group)
	control, err := cgroups.Load(cgroups.V1, cgroups.StaticPath(name))
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(control.Processes(cgroups.Name(group), true))
}
```

Then you can run and got the panic:
```
mkdir /sys/fs/cgroup/cpu/my-test
go run main.go
```

**Comment by fuweid** [comment]
Hmm. The StaticPath doesn't check the path. We can fix with returning ErrControllerNotActive if it is nil. Could you mind to file pr to fix it? Thanks

**Comment by linrl3** [comment]
Sure. Will do it in a few days 👌

**Comment by linrl3** [comment]
Hi @fuweid,

Please review the PR https://github.com/containerd/cgroups/pull/206. Thank you!

**Comment by fuweid** [comment]
close by #207
