### ISSUE TITLE
Use Cirrus CI instead of Linux-on-macOS hack

### ISSUE THREAD

**Issue by kzys** [containerd/cgroups#222]
https://github.com/containerd/containerd/issues/6542

> We have been using Vagrant on macOS on GHA for testing Fedora 35, but we are not happy with its performance and flakiness. So probably we should use Cirrus CI.

Maybe we should do the same here?

**Comment by estesp** [comment]
Definitely possible if we need to; cgroups v2 tests are much less intensive than the containerd overall project. My PR that just updated Go and the Fedora version ran vagrant + tests in 3 minutes (compared to ~35-40 minutes for all the setup and tests in the core containerd project CI).

If it gets flakier then maybe we should consider, but I don't think we've had as much issue here until the ones I saw failing today. Definitely easier from a project admin. standpoint to stick with all GitHub Actions based if we can.

**Comment by kzys** [comment]
Yeah. It is surprising to see #223 worked just fine. Maybe our VM was too small?

Regarding GitHub Actions, we might be able to use https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners as well.

**Comment by kzys** [comment]
Resolved by https://github.com/containerd/cgroups/pull/237.
