### ISSUE TITLE
Support `cgroup.kill` in cgroupv2 manager

### ISSUE THREAD

**Issue by jseba** [containerd/cgroups#229]
Kernel 5.14 added support for a `cgroup.kill` file in cgroupv2; writing "1" to this file will immediately send SIGKILL to all processes in that cgroup hierarchy.

I have a local change to support this feature in this library but I wasn't sure which way would be the preferred method. I'm currently checking the kernel release information from `uname(2)` to see if the kernel version has the feature, but this is expensive (handled by a sync.Once wrapper) and I can't be sure that no-one will backport this to an older kernel (not likely but not not a possibility).

The other approach would be to just blindly send the write out and if an error is returned, just assume it's not supported and tell the caller that. An improved variant of this approach would be to have a fallback that walks the processes in the cgroup hierarchy and freezes/kills/thaws them (this is the approach used by libcontainer in runc).

**Comment by dcantah** [comment]
@jseba Write -> fail -> fallback to libcontainer approach sounds fine to me. Do you still have a workable branch?

**Comment by dcantah** [comment]
@jseba I made a change here with this work: https://github.com/containerd/cgroups/pull/263

**Comment by dcantah** [comment]
#263 was checked in, closing this
