### ISSUE TITLE
cgroup v1 rdma.current 

### ISSUE THREAD

**Issue by elee1766** [containerd/cgroups#276]
hi!

i've been trying to use this package to detect the resource constraints of my container running on kubernetes. I'm getting this issue both with DOKS (digitalocean) and GKE (google). 

I can load the cgroupv2 fine, locating and creating a manager for it. However, when i call "Stats"  https://github.com/containerd/cgroups/blob/main/cgroup2/manager.go#L527 on the manager, i get
`open /sys/fs/cgroup/rdma/rdma.current: no such file or directory`

this seems to happen when it tries to read that file https://github.com/containerd/cgroups/blob/main/cgroup2/manager.go#L620

so i exec into the pod that is running, and i verify we support cgroup v2
```
/sys/fs/cgroup #  grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
```

but i don't see rdma.current in my rdma directory
```
/sys/fs/cgroup # ls /sys/fs/cgroup/rdma
cgroup.clone_children  cgroup.procs           cgroup.sane_behavior   notify_on_release      release_agent          tasks
```

at a higher level, i am attempting to integrate cgroup v2 support to this package https://github.com/raulk/go-watchdog/pull/22

is something configured wrong/am i loading the wrong cgroup/doing something else wrong? It's odd because the same code works when i am using `docker run` on my local machine. any help would be really appreciated.

happy to provide any info if needed

**Comment by dcantah** [comment]
Wait, you said you're loading and calling stat on the cgroup2 manager, but the path it's trying to open is a cgroup1 path which is odd. The cgroup 2 codepath doesn't error out on the only instance of trying to read the equivalent file in the cgroup: https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup2/manager.go#L606. Are you sure you're loading a cgroup2 mountpoint?

**Comment by elee1766** [comment]
oh. i see. this is probably my mistake then. It seems the underlying nodes support unified cgroups but within the container is only supporting legacy? that must have confused me.

I am probably then just doing cgroup1 path wrong? I will debug and close the issue in a bit if im just being stupid. really appreciate the help!!

**Comment by dcantah** [comment]
No worries, not stupid at all. I'm curious to know the outcome!

**Comment by mmerkes** [comment]
Can this issue be closed? Doesn't like like an issue with the package.

**Comment by elee1766** [comment]
yuh
