### ISSUE TITLE
Stat in cpu and cpuacct in cgroupv1 may access nil pointer

### ISSUE THREAD

**Issue by wfly1998** [containerd/cgroups#289]
Noticed that there is a comment in `cpuController.Stat`:

https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup1/cpu.go#L102-L125

As mentioned here, the `stats.CPU` may be shared between `cpu` and `cpuacct`, so it cannot be set directly like `memory`:

https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup1/memory.go#L240-L245

But the `stats.CPU` and `stats.CPU.Usage` may be `nil` and the current code will access it without any checks:

https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup1/cpuacct.go#L52-L70

Is it necessary to add a check for it?  I think checking it and assigning something if it is `nil` is a good solution.

**Comment by mmerkes** [comment]
From what I can tell, this is not an issue. When we initialize the `stats *v1.Metrics`, we initialize `stats.CPU` and `stats.CPU.Usage`:

https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup1/cgroup.go#L308-L313

While it would be more defensive to make the check inside the system `Stat` code, it's not necessary. Besides that, if it could happen, seems likely that it'd be a big enough miss that we'd also have reports of errors.

Looks like we can close this issue.
