### ISSUE TITLE
oom killer cannot be re-enabled

### ISSUE THREAD

**Issue by kestrelcjx** [containerd/cgroups#307]
https://github.com/containerd/cgroups/blob/a0ae1c2a2c40df548614588dd079a4a790971918/cgroup1/memory.go#L454

**Comment by kestrelcjx** [comment]
https://github.com/containerd/cgroups/blob/a0ae1c2a2c40df548614588dd079a4a790971918/cgroup1/memory.go#L453-L459

**Comment by dcantah** [comment]
Fixed via https://github.com/containerd/cgroups/pull/311
