### ISSUE TITLE
ToResources method has a bug in the conversion of swap memory limits.

### ISSUE THREAD

**Issue by kestrelcjx** [containerd/cgroups#309]
https://github.com/containerd/cgroups/blob/a0ae1c2a2c40df548614588dd079a4a790971918/cgroup2/utils.go#L155-L187

**Comment by kestrelcjx** [comment]
<img width="1167" alt="截屏2023-11-28 上午11 11 58" src="https://github.com/containerd/cgroups/assets/38725513/28b4f3bc-3ace-40b2-a13b-d9968bc42e54">

**Comment by kestrelcjx** [comment]
https://github.com/containerd/cgroups/blob/a0ae1c2a2c40df548614588dd079a4a790971918/cgroup2/utils.go#L178C2-L178C2
resources.Memory.Swap may need to be changed to swap-max

**Comment by dcantah** [comment]
Fixed via https://github.com/containerd/cgroups/pull/314
