### ISSUE TITLE
Release 3.0.3

### ISSUE THREAD

**Issue by zouyee** [containerd/cgroups#317]
The tag 3.0.2 has been created for approximately six months，at present, the main branch's additions primarily consist of psi metrics, export memory and swap max usage and ebpf update

- https://github.com/containerd/cgroups/pull/315
- https://github.com/containerd/cgroups/pull/308
- https://github.com/containerd/cgroups/pull/305
- https://github.com/containerd/cgroups/pull/304

@AkihiroSuda Can we create a new tag, 3.0.3?

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/cgroups/releases/tag/v3.0.3
