### ISSUE TITLE
Release plan for 3.0.4

### ISSUE THREAD

**Issue by AlbertoBarba** [containerd/cgroups#350]
Is there any plan to tag version 3.0.4?
3.0.3 has been tagged the last December and main branch contains different useful changes (EG: https://github.com/containerd/cgroups/pull/321)
@AkihiroSuda

**Comment by AkihiroSuda** [comment]
The CI has to be fixed before making a release
- https://github.com/containerd/cgroups/issues/351

**Comment by AkihiroSuda** [comment]
Let's bump up go.mod too
- https://github.com/containerd/cgroups/pull/353

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/cgroups/releases/tag/v3.0.4

**Comment by AlbertoBarba** [comment]
Thanks @AkihiroSuda
