### ISSUE TITLE
tagged release versions

### ISSUE THREAD

**Issue by adnxn** [containerd/cgroups#46]
Would it be possible to have tagged versioned releases for this repo? Is there a reason why we're explicitly choosing to not have versioned releases? LMK if it's just a matter of doing the work, I could make those changes.

I think it would improve ux for at least those projects using dep to manage containerd/cgroups as a dependency.

**Comment by crosbymichael** [comment]
Ya, we can start tagging releases.  We have one open PR then I'll tag a new release when its merged in.
