### ISSUE TITLE
cgroups: cgroup deleted

### ISSUE THREAD

**Issue by rkakrik** [containerd/cgroups#47]
Can't load cgroup with this code:
`control, err := cgroups.Load(cgroups.Systemd, cgroups.Slice("user.slice", "user-1000"))`
("/user.slice/user-1000.slice" exists)

**Comment by rkakrik** [comment]
System: Archlinux
Kernel: 4.16.2
SystemD: 238.76
```
mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
```

**Comment by crosbymichael** [comment]
Ya.  It looks like there is a bug with now the slice name is concatenated.  You can see how it's adding `.slice` to your `user-1000`.

**Comment by crosbymichael** [comment]
Ya.  It looks like there is a bug with now the slice name is concatenated.  You can see how it's adding `.slice` to your `user-1000`.

**Comment by crosbymichael** [comment]
@rkakrik what do you think about changing the function to take the fully path?  it breaks the api but since it's already broken it seems like the best long term fix for this issue.

**Comment by AnushaY1** [comment]
i am also facing same issue
control, err := cgroups.Load(cgroups.Systemd, cgroups.Slice("system.slice", "sshd.service"))

**Comment by crosbymichael** [comment]
@AnushaY1 @rkakrik the bug is happening here: https://github.com/containerd/cgroups/blob/master/systemd.go#L57

If one of you want to try to fix it and test that would be helpful.  It should be pretty straightforward.
