### ISSUE TITLE
Cannot develop on Mac OS X due to OS dependency

### ISSUE THREAD

**Issue by mback2k** [containerd/cgroups#55]
Working with Visual Studio Code on OS X during development leads to the following errors:

```
# github.com/containerd/cgroups
../../containerd/cgroups/memory.go:179:33: undefined: unix.SYS_EVENTFD2
../../containerd/cgroups/memory.go:179:55: undefined: unix.EFD_CLOEXEC
```

Would it be possible to make these declarations optional during development on another plattform?

**Comment by crosbymichael** [comment]
Hi, thanks for making the issue instead of just changing it ;) 

Humm, this is kinda tricky because cgroups are linux only so I'm not sure we want to modify code to support a development usecase like this.  Not that we wouldn't love your contributions, it just feels a little off to me to change a linux only codebase to support OSX, only for development.

**Comment by mback2k** [comment]
Hi, thanks for your response. This makes total sense, I just have to figure out how to tell the VSCode toolchain to use GOOS=linux for linting and testing. :)

**Comment by crosbymichael** [comment]
@mback2k thanks for being understanding.  Let me know if you need anything else.

**Comment by SamYuan1990** [comment]
as a Mac user for open source development.
I do agree and understand that cgroup is linux specific for runtime, and we must use real path as OS dependency.
but I want to know if we can provide any mock approach so that Mac user able to coding with mock data?

**Comment by SamYuan1990** [comment]
For a specific example, following test driven development
- For test case
I want to mock a cgroup at a specific path, as preparation.
- For code logic:
I want to load the cgroup from the specific path.
I want to read data from the mock.

**Comment by SamYuan1990** [comment]
The reason I asked again is that
```
yuanyi@yuanyideMacBook-Pro cgroup_imp % ls /run/systemd/private
ls: /run/systemd/private: No such file or directory
yuanyi@yuanyideMacBook-Pro cgroup_imp % ls /sys/fs/cgroup/
ls: /sys/fs/cgroup/: No such file or directory
```
on my mac book...
