### ISSUE TITLE
unable to find * in controller set: unknown

### ISSUE THREAD

**Issue by tonistiigi** [containerd/cgroups#76]
There are problems with this library handling missing cgroups or the way they are mounted. The unhandled configuration seems to become common with new systemd.

These issues list the output of mount and proc in the affected systems:

https://github.com/docker/for-linux/issues/545
https://github.com/docker/for-linux/issues/552

@crosbymichael

**Comment by crosbymichael** [comment]
ok, do you have a good way to reproduce this?  some cloud vm?

**Comment by tonistiigi** [comment]
I don't. The issues above have descriptions of setups where users have hit this. @andrewhsu did you try/manage to reproduce this?

**Comment by ranisalt** [comment]
> ok, do you have a good way to reproduce this?

It fails as described on a clean Arch Linux install with up to date systemd (v240 or v241).
