### ISSUE TITLE
Add network metrics

### ISSUE THREAD

**Issue by ZeroMagic** [containerd/cgroups#80]
When we use containerd to run our applications, we can not collect the network metrics about containers. Can we add the network metrics into metrics.proto? 

```go
type NetworkInterface struct {
	// Name is the name of the network interface.
	Name string

	RxBytes   uint64
	RxPackets uint64
	RxErrors  uint64
	RxDropped uint64
	TxBytes   uint64
	TxPackets uint64
	TxErrors  uint64
	TxDropped uint64
}
```

ping @crosbymichael

**Comment by crosbymichael** [comment]
Where are these metrics going to come from?

**Comment by ZeroMagic** [comment]
> Where are these metrics going to come from?

@crosbymichael 
Currently KataContainers collect the metrics from [libcontainer Stats() API](https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L175). 

The libcontainer Stats() API has collected the network metrics. However KataContainers do not transfer the network metrics now. I will propose a similar issue in KataContainers community.

Then the network metrics will come from [shimV2 Stats() API](https://github.com/kata-containers/runtime/blob/master/containerd-shim-v2/service.go#L776).

**Comment by crosbymichael** [comment]
The reason why I kept network stats out of this pkg is because a lot of the network stats come from `/sys` and not cgroups

**Comment by ZeroMagic** [comment]
I got it. Where do you think I should add network stats?  
Sincerely looking forward to some guidance.

**Comment by thaJeztah** [comment]
@ZeroMagic with https://github.com/containerd/cgroups/pull/81 merged; is this one ready too close?
