### ISSUE TITLE
provide build metrics.proto guide in README?

### ISSUE THREAD

**Issue by woshijpf** [containerd/cgroups#87]
I want to add some Stats struct in metrics.proto file and generate a new metrics.proto.go file, however, I can not find Makefile or any guide or steps to introduce how to compile proto file, can anybody provide some guide?

**Comment by crosbymichael** [comment]
@woshijpf I opened up a PR to add a makefile that will generate the protos for you.  You will need protobuild and protobufs installed to do this.
